// import { Inter } from "next/font/google";

// import { ThemeProvider } from "@/components/ThemeProvide";
import Navbar from "@/components/layout/navbar";
import { ThemeProvider } from "../components/ThemeProvide";
import "./globals.css";
import Footer1 from "@/components/layout/footer1";
import Footer from "@/components/layout/footer";
// import { ThemeProvider } from "../components/ThemeProvide";
// import Navbar from "@/src/components/layout/navbar";

// import Footer from "../components/layout/footer";
// import Footer1 from "../components/layout/footer1";

// const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head>
          <style>
          @import url('https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap');
          </style>
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
          <link
            href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
            rel="stylesheet"
          />
        </head>
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            {children}
            <Footer1 />
            <Footer /> 
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
